---
- name: EDA | Kafka | Listen for events on a Kafka topic
  hosts: localhost

  sources:
    - ansible.eda.kafka:
        host: kafka
        port: 9092
        topic: eda-topic

  rules:
    - name: EDA | Kafka | Run playbook to greet our Kafka peers
      condition: event.body.name == "greeting"
      actions:
        - set_fact:
            fact:
              kafkagreeting: "{{ event.body.message }}"

        - run_job_template:
            name: "[EDA] Kafka playbook"
            organization: Default
            job_args:
              extra_vars:
                greeting: "{{ event.body.message }}"
