---
- name: EDA | Insights | Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002
        token: redhatinsightstoken

  rules:
    - name: EDA | Insights | Detect and remediate recommendation event from Insights
      condition: event.payload.event_type == "new-recommendation"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights - Remediate SSH root login"
            organization: Default
            job_args:
              extra_vars:
                insights_recommendation: "{{ event.payload.events.0.payload.rule_id }}"

    - name: EDA | Insights | Simple type report
      condition: event.payload is defined
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights playbook"
            organization: Default
            job_args:
              extra_vars:
                insights_event_type: "{{ event.payload.events.0.payload.event_type }}"
