version: "3.8"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    hostname: zookeeper
    networks:
      - eda-ansible
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    networks:
      - eda-ansible
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      ALLOW_PLAINTEXT_LISTENER: true
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://<ADVERTISED_HOST/IP>:<PORT>"
      KAFKA_ENABLE_KRAFT: false
    depends_on:
      - zookeeper

  alertmanager:
    image: quay.io/kubealex/eda-alertmanager
    ports: "9093:9093"
    hostname: alertmanager
    networks:
      - eda-ansible
    volumes:
      - ./alertmanager/:/etc/alertmanager:Z

  mosquitto:
    image: docker.io/library/eclipse-mosquitto
    ports: "1883:1883"
    hostname: mosquitto
    networks:
      - eda-ansible
    volumes:
      - ./mosquitto/:/mosquitto/config/:Z

networks:
  eda-ansible:
    name: eda-ansible

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
